[REF] account_journal_restrict_mode: run tests separately
Fixes
```
ERROR odoo odoo.addons.account_journal_lock_date.tests.test_journal_lock_date: FAIL: TestJournalLockDate.test_journal_lock_date
odoo.exceptions.UserError: This document is protected by a hash. Therefore, you cannot edit the following fields: Number.
```